# -*- coding: utf-8 -*-
"""Pytest-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_zcyzs5NscAmguSIq2cRIBUdKahB9Yw
"""

!pip -q install pytest pytest-sugar

# Commented out IPython magic to ensure Python compatibility.
#move to tdd directory

from pathlib import Path
if Path.cwd().name != 'tdd':
#   %mkdir tdd
#   %cd tdd

# %pwd

# Commented out IPython magic to ensure Python compatibility.
# clean all files
# %rm *.py

#Create a file a test file test_math.py

# Commented out IPython magic to ensure Python compatibility.
# 
# %%file test_math.py
# 
# import math
# def test_sqrt():
#   assert math.sqrt(4) == 2.0
# 
# def test_add():
#   assert 1+1 == 2
# 
# def test_divide():
#   assert 10/2 == 5
# 
#

!python -m pytest test_math.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_model.py
# import numpy as np
# import pickle
# from sklearn.datasets import load_iris
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, classification_report
# 
# # -------------------------
# # Load dataset
# # -------------------------
# iris = load_iris()
# X = iris.data        # Features
# y = iris.target      # Labels
# 
# # -------------------------
# # Train-Test Split
# # -------------------------
# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )
# 
# # -------------------------
# # Train Logistic Regression
# # -------------------------
# model = LogisticRegression(max_iter=200)
# model.fit(X_train, y_train)
# 
# # -------------------------
# # Predictions
# # -------------------------
# y_pred = model.predict(X_test)
# 
# # -------------------------
# # Accuracy
# # -------------------------
# accuracy = accuracy_score(y_test, y_pred)
# print(f"Accuracy: {accuracy:.2f}")
# 
# # -------------------------
# # Detailed Report
# # -------------------------
# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))
# 
# # -------------------------
# # Save model
# # -------------------------
# with open("iris_logistic_model.pkl", "wb") as f:
#     pickle.dump(model, f)
# 
# print("\nModel saved as iris_logistic_model.pkl")
# def test_model_training():
#   assert model is not None, "Model training failed!"
# 
# def est_prediction_shape():
#   predictions = model.predict(X_test)
#   assert predictions.shape[0] == y_test.shape[0], "Prediction shape mismatch!"
# 
# def test_model_accuracy():
#     # Sample test data
#     X = np.array([
#         [5.1, 3.5, 1.4, 0.2],
#         [6.2, 3.4, 5.4, 2.3],
#         [5.9, 3.0, 5.1, 1.8]
#     ])
# 
#     y_true = np.array([0, 2, 2])
# 
#     y_pred = model.predict(X)
# 
#     acc = accuracy_score(y_true, y_pred)
# 
#     assert acc >= 0.7, f"Accuracy too low: {acc}"
# 
# 
# def test_model_correctness():
#     # Known input from Iris dataset
#     X = np.array([[5.1, 3.5, 1.4, 0.2]])
# 
#     y_pred = model.predict(X)
# 
#     # Expected class = 0 (setosa)
#     assert y_pred[0] == 0, f"Incorrect prediction: {y_pred[0]}"
# 
# 
# import time
# 
# def test_model_performance():
#     X = np.array([[5.1, 3.5, 1.4, 0.2]])
# 
#     start = time.time()
#     model.predict(X)
#     end = time.time()
# 
#     latency = end - start
# 
#     assert latency < 0.01, f"Prediction too slow: {latency} sec"
# 
# 
# def test_model_persistence():
#   # Save the trained model
#   with open('iris_logistic_model.pkl', 'wb') as f:
#     pickle.dump(model, f)
# 
#   # Load the model
#   with open('iris_logistic_model.pkl', 'rb') as f:
#     loaded_model = pickle.load(f)
# 
#   assert loaded_model is not None, "Loaded model is None!"
#   assert isinstance(loaded_model, LogisticRegression), "Loaded model is not LogisticRegression!"
# 
# def test_saved_model_predictions():
#   # Load the model
#   with open('iris_logistic_model.pkl', 'rb') as f:
#     loaded_model = pickle.load(f)
# 
#   # Make predictions with the original model
#   original_predictions = model.predict(X_test)
# 
#   # Make predictions with the loaded model
#   loaded_predictions = loaded_model.predict(X_test)
# 
#   assert np.array_equal(original_predictions, loaded_predictions), "Predictions from original and loaded models do not match!"
# 
# 
# 
# #AP to

!pytest test_model.py