# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJSaxuR3UuG7EXYAmThvEv0y8agdGjBc
"""

import config

def main():
    settings = config.Config.get_config()

    print("Application Configuration:")
    for key, value in settings.items():
        print(f"{key}: {value}")


if __name__ == "__main__":
    main()