# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkE2qjb1LMTlRVvLp2L7AdUCGYp3tN1c
"""

class Config:

    DEBUG = True
    LOG_LEVEL = "INFO"

    DATASET_PATH = "linear_regression_dataset.csv"
    MODEL_PATH = "linear_regression_model.pkl"

    # -------------------------
    # Model Parameters (optional)
    # -------------------------
    RANDOM_STATE = 42
    TEST_SIZE = 0.2
    @staticmethod
    def get_config():
        return {
            "debug": Config.DEBUG,
            "log_level": Config.LOG_LEVEL,
            "dataset_path": Config.DATASET_PATH,
            "model_path": Config.MODEL_PATH,
            "random_state": Config.RANDOM_STATE,

        }